import type {
  CaliforniaPrivacyEvidence,
  CpraCbaOptOutEvidence,
  GpcVerification
} from "../types/snapshots";

export const CALIFORNIA_PRIVACY_RUNTIME_ARTIFACT_CONTRACT_VERSION = "wc01.california_privacy_runtime.v1" as const;

export type CaliforniaPrivacyRuntimeArtifactContractVersion =
  typeof CALIFORNIA_PRIVACY_RUNTIME_ARTIFACT_CONTRACT_VERSION;

export type CaliforniaPrivacyRuntimeArtifactContract = {
  californiaPrivacyEvidence: CaliforniaPrivacyEvidence;
  contractVersion: CaliforniaPrivacyRuntimeArtifactContractVersion;
  cpraCbaOptOutEvidence: CpraCbaOptOutEvidence | null;
  gpcVerification: GpcVerification | null;
};

export const CALIFORNIA_PRIVACY_RUNTIME_ARTIFACT_REQUIRED_KEYS = [
  "californiaPrivacyEvidence",
  "cpraCbaOptOutEvidence",
  "gpcVerification"
] as const;

export const CALIFORNIA_PRIVACY_RUNTIME_ARTIFACT_FIELD_FAMILIES = {
  adtech_sharing_runtime: [
    "californiaPrivacyEvidence.targetedAdvertisingSignalsObserved",
    "californiaPrivacyEvidence.advertisingSharingVendors",
    "californiaPrivacyEvidence.saleShareRequestUrls",
    "cpraCbaOptOutEvidence.cbaVendorTier1",
    "cpraCbaOptOutEvidence.advertisingSharingVendors"
  ],
  collection_notice: [
    "californiaPrivacyEvidence.collectionContextObserved",
    "californiaPrivacyEvidence.collectionContextUrls",
    "californiaPrivacyEvidence.collectionNoticeCueObserved",
    "californiaPrivacyEvidence.collectionNoticeCueText"
  ],
  gpc_handling: [
    "californiaPrivacyEvidence.gpcTestRan",
    "californiaPrivacyEvidence.gpcSignalSent",
    "californiaPrivacyEvidence.gpcRecognitionObserved",
    "gpcVerification.status",
    "gpcVerification.trackerCountDelta",
    "gpcVerification.thirdPartyCookieCountDelta",
    "gpcVerification.policyMentions"
  ],
  notice_surface: [
    "californiaPrivacyEvidence.privacyNoticeObserved",
    "californiaPrivacyEvidence.privacyNoticeUrls",
    "californiaPrivacyEvidence.californiaNoticeCueObserved",
    "californiaPrivacyEvidence.californiaNoticeCueText"
  ],
  rights_methods: [
    "californiaPrivacyEvidence.consumerRightsRequestMethodObserved",
    "californiaPrivacyEvidence.consumerRightsRequestMethodUrls",
    "californiaPrivacyEvidence.consumerRightsRequestMethodTypes",
    "californiaPrivacyEvidence.consumerRightsRequestMethodSnippets"
  ],
  sale_share_control: [
    "californiaPrivacyEvidence.doNotSellSharePathObserved",
    "californiaPrivacyEvidence.doNotSellSharePathUrl",
    "californiaPrivacyEvidence.doNotSellSharePathLabel",
    "californiaPrivacyEvidence.privacyChoicePathEvidence",
    "californiaPrivacyEvidence.privacyChoiceInteractionEvidence",
    "cpraCbaOptOutEvidence.choiceControlsInspected",
    "cpraCbaOptOutEvidence.optOutUiResult",
    "cpraCbaOptOutEvidence.optOutControlFound",
    "cpraCbaOptOutEvidence.privacyChoiceSearchUrls"
  ],
  opt_out_friction: [
    "californiaPrivacyEvidence.doNotSellSharePathObserved",
    "californiaPrivacyEvidence.privacyChoicePathEvidence",
    "californiaPrivacyEvidence.privacyChoiceInteractionEvidence",
    "californiaPrivacyEvidence.privacyChoiceInteractionEvidence.preferenceCenterProbeUrl",
    "californiaPrivacyEvidence.privacyChoiceInteractionEvidence.preferenceCenterProbeFinalUrl",
    "californiaPrivacyEvidence.privacyChoiceInteractionEvidence.preferenceCenterProbeAttempts",
    "californiaPrivacyEvidence.privacyChoiceInteractionEvidence.preferenceCenterProbeErrorCategory",
    "californiaPrivacyEvidence.privacyChoiceInteractionEvidence.preferenceCenterProbeReason",
    "californiaPrivacyEvidence.privacyChoiceInteractionEvidence.preferenceCenterVisibleTextSnippets",
    "californiaPrivacyEvidence.privacyChoiceInteractionEvidence.preferenceActionCandidateCount",
    "californiaPrivacyEvidence.privacyChoiceInteractionEvidence.preferenceActionCandidateLabels",
    "californiaPrivacyEvidence.privacyChoiceInteractionEvidence.preferenceSaveCandidateCount",
    "californiaPrivacyEvidence.privacyChoiceInteractionEvidence.preferenceSaveCandidateLabels",
    "californiaPrivacyEvidence.privacyChoiceInteractionEvidence.preferenceToggleCandidateCount",
    "californiaPrivacyEvidence.privacyChoiceInteractionEvidence.preferenceToggleCandidateLabels",
    "californiaPrivacyEvidence.optOutFrictionSignals",
    "californiaPrivacyEvidence.optOutInteractionSteps"
  ],
  post_opt_out_tracking: [
    "californiaPrivacyEvidence.optOutInteractionConfirmed",
    "californiaPrivacyEvidence.postOptOutTrackingReductionObserved",
    "californiaPrivacyEvidence.postOptOutTrackingPersisted",
    "californiaPrivacyEvidence.privacyChoiceInteractionEvidence",
    "californiaPrivacyEvidence.postOptOutPersistedVendors",
    "californiaPrivacyEvidence.postOptOutRequestUrls"
  ],
  sensitive_pi: [
    "californiaPrivacyEvidence.sensitivePiContextObserved",
    "californiaPrivacyEvidence.sensitivePiCategories",
    "californiaPrivacyEvidence.sensitivePiContextUrls",
    "californiaPrivacyEvidence.sensitiveThirdPartyTrackingObserved",
    "californiaPrivacyEvidence.sensitiveThirdPartyTrackingVendors",
    "californiaPrivacyEvidence.limitUseSensitivePiPathObserved",
    "californiaPrivacyEvidence.limitUseSensitivePiPathUrl"
  ]
} as const;

export const CALIFORNIA_PRIVACY_RUNTIME_ARTIFACT_FIXTURES = {
  evidenceRichReviewSignal: {
    contractVersion: CALIFORNIA_PRIVACY_RUNTIME_ARTIFACT_CONTRACT_VERSION,
    californiaPrivacyEvidence: {
      advertisingSharingVendors: ["Example Ads", "Meta Pixel"],
      californiaNoticeCueObserved: true,
      californiaNoticeCueText: "California residents can learn more in our California privacy notice.",
      collectionContextObserved: true,
      collectionContextTypes: ["newsletter_signup"],
      collectionContextUrls: ["https://example.test/newsletter"],
      collectionNoticeCueObserved: true,
      collectionNoticeCueText: "By submitting this form, you agree to our Privacy Notice.",
      consumerRightsRequestMethodObserved: true,
      consumerRightsRequestMethodSnippets: [
        "Submit a privacy request to access, delete, or correct your personal information."
      ],
      consumerRightsRequestMethodTypes: ["access_request", "delete_request", "correction_request"],
      consumerRightsRequestMethodUrls: ["https://example.test/privacy-request"],
      doNotSellShareLabels: [],
      doNotSellSharePathLabel: null,
      doNotSellSharePathObserved: false,
      doNotSellSharePathUrl: null,
      doNotSellShareUrls: [],
      evidenceRefs: [
        "runtime_artifact:california_privacy:homepage",
        "runtime_artifact:privacy_choice_search:footer_privacy_surfaces"
      ],
      gpcRecognitionObserved: false,
      gpcSignalSent: true,
      gpcTestRan: true,
      gpcTrackingReductionObserved: false,
      limitUseSensitivePiPathLabel: null,
      limitUseSensitivePiPathObserved: false,
      limitUseSensitivePiPathUrl: null,
      optOutInteractionConfirmed: null,
      policyRuntimeDisclosureAlignment: "review",
      policyRuntimeDisclosureSnippets: [
        "We may disclose personal information for targeted advertising and analytics."
      ],
      postOptOutTrackingPersisted: null,
      postOptOutTrackingReductionObserved: null,
      privacyChoiceLabels: [],
      privacyChoiceUrls: [],
      privacyControlAccessibilityIssueObserved: null,
      privacyControlAccessibilitySignals: [],
      privacyNoticeObserved: true,
      privacyNoticeSourceUrls: ["https://example.test/privacy"],
      privacyNoticeUrls: ["https://example.test/privacy"],
      saleShareCookieNames: ["_fbp"],
      saleShareRequestUrls: ["https://connect.facebook.net/en_US/fbevents.js"],
      saleShareRuntimeSignalsObserved: true,
      sensitivePiCategories: ["financial_information"],
      sensitivePiContextObserved: true,
      sensitivePiContextUrls: ["https://example.test/checkout"],
      sensitiveThirdPartyTrackingObserved: true,
      sensitiveThirdPartyTrackingRequestUrls: ["https://connect.facebook.net/tr"],
      sensitiveThirdPartyTrackingVendors: ["Meta Pixel"],
      targetedAdvertisingSignalsObserved: true,
      unmatchedRuntimeDisclosureVendors: ["Example Ads"]
    },
    cpraCbaOptOutEvidence: {
      advertisingSharingVendors: ["Example Ads", "Meta Pixel"],
      cbaVendorTier1: ["connect.facebook.net"],
      cbaVendorTier2: [],
      choiceControlSearchScope: "homepage_footer_privacy_surfaces",
      choiceControlsInspected: true,
      cpraIconDetected: false,
      findingSeverity: "high",
      gpcCbaHonored: false,
      gpcOptOutDiscoveryAttemptUrls: ["https://example.test/privacy"],
      limitation: "homepage_only",
      optOutControlFound: false,
      optOutLinkHref: null,
      optOutLinkText: null,
      optOutUiResult: "absent",
      pageUrl: "https://example.test/",
      policyCbaLanguage: "full_cba_language",
      policyUiCongruent: false,
      privacyChoiceSearchUrls: ["https://example.test/privacy"],
      scanOriginGeo: "US-CA",
      suppressorApplied: null
    },
    gpcVerification: {
      baselineThirdPartyCookieCount: 8,
      baselineTrackerCount: 5,
      evidenceUrls: ["https://example.test/", "https://example.test/privacy"],
      gpcRecognitionObserved: false,
      gpcSignalSent: true,
      gpcThirdPartyCookieCount: 9,
      gpcTrackerCount: 6,
      policyMentions: ["We honor Global Privacy Control opt-out preference signals."],
      status: "ignored",
      thirdPartyCookieCountDelta: 1,
      trackerCountDelta: 1
    }
  },
  observedControlsOnly: {
    contractVersion: CALIFORNIA_PRIVACY_RUNTIME_ARTIFACT_CONTRACT_VERSION,
    californiaPrivacyEvidence: {
      advertisingSharingVendors: [],
      collectionContextObserved: false,
      collectionContextUrls: [],
      collectionNoticeCueObserved: null,
      consumerRightsRequestMethodObserved: true,
      consumerRightsRequestMethodSnippets: ["Use our privacy portal to access or delete personal information."],
      consumerRightsRequestMethodTypes: ["privacy_portal"],
      consumerRightsRequestMethodUrls: ["https://example.test/privacy/portal"],
      doNotSellShareLabels: ["Your Privacy Choices"],
      doNotSellSharePathLabel: "Your Privacy Choices",
      doNotSellSharePathObserved: true,
      doNotSellSharePathUrl: "https://example.test/privacy/choices",
      doNotSellShareUrls: ["https://example.test/privacy/choices"],
      evidenceRefs: ["runtime_artifact:california_privacy:privacy_controls"],
      gpcRecognitionObserved: true,
      gpcSignalSent: true,
      gpcTestRan: true,
      gpcTrackingReductionObserved: true,
      limitUseSensitivePiPathLabel: null,
      limitUseSensitivePiPathObserved: null,
      limitUseSensitivePiPathUrl: null,
      optOutInteractionConfirmed: true,
      policyRuntimeDisclosureAlignment: "aligned",
      postOptOutTrackingPersisted: false,
      postOptOutTrackingReductionObserved: true,
      privacyChoiceLabels: ["Your Privacy Choices"],
      privacyChoiceUrls: ["https://example.test/privacy/choices"],
      privacyControlAccessibilityIssueObserved: false,
      privacyControlAccessibilitySignals: [],
      privacyNoticeObserved: true,
      privacyNoticeSourceUrls: ["https://example.test/privacy"],
      privacyNoticeUrls: ["https://example.test/privacy"],
      saleShareRuntimeSignalsObserved: false,
      sensitivePiCategories: [],
      sensitivePiContextObserved: false,
      targetedAdvertisingSignalsObserved: false
    },
    cpraCbaOptOutEvidence: null,
    gpcVerification: {
      baselineThirdPartyCookieCount: 3,
      baselineTrackerCount: 1,
      evidenceUrls: ["https://example.test/privacy/choices"],
      gpcRecognitionObserved: true,
      gpcSignalSent: true,
      gpcThirdPartyCookieCount: 1,
      gpcTrackerCount: 0,
      policyMentions: ["Global Privacy Control signals are honored."],
      status: "honored",
      thirdPartyCookieCountDelta: -2,
      trackerCountDelta: -1
    }
  },
  observedPostOptOutReduction: {
    contractVersion: CALIFORNIA_PRIVACY_RUNTIME_ARTIFACT_CONTRACT_VERSION,
    californiaPrivacyEvidence: {
      advertisingSharingVendors: ["Tealium"],
      collectionContextObserved: false,
      collectionContextUrls: [],
      collectionNoticeCueObserved: null,
      consumerRightsRequestMethodObserved: true,
      consumerRightsRequestMethodSnippets: ["Use the privacy portal to submit access, deletion, and correction requests."],
      consumerRightsRequestMethodTypes: ["privacy_portal"],
      consumerRightsRequestMethodUrls: ["https://example.test/privacy/us"],
      doNotSellShareLabels: ["Do not sell or share my personal information"],
      doNotSellSharePathLabel: "Do not sell or share my personal information",
      doNotSellSharePathObserved: true,
      doNotSellSharePathUrl: "https://example.test/privacy/us",
      doNotSellShareUrls: ["https://example.test/privacy/us"],
      evidenceRefs: ["runtime_artifact:california_privacy:confirmed_opt_out"],
      gpcRecognitionObserved: true,
      gpcSignalSent: true,
      gpcTestRan: true,
      gpcTrackingReductionObserved: true,
      limitUseSensitivePiPathLabel: null,
      limitUseSensitivePiPathObserved: null,
      limitUseSensitivePiPathUrl: null,
      optOutInteractionConfirmed: true,
      policyRuntimeDisclosureAlignment: "aligned",
      postOptOutPersistedVendors: [],
      postOptOutRequestUrls: ["https://example.test/cdn/essential.js"],
      postOptOutTrackingPersisted: false,
      postOptOutTrackingReductionObserved: true,
      privacyChoiceInteractionEvidence: {
        afterThirdPartyCookieCount: 1,
        afterTrackerCount: 0,
        attempted: true,
        beforeThirdPartyCookieCount: 4,
        beforeTrackerCount: 1,
        clickAttempted: true,
        clickConfirmed: true,
        clickDepth: 1,
        evidenceRefs: ["california_privacy_choice_exercise", "privacy_choice_control_clicked"],
        evidenceUrls: ["https://tags.example.test/tealium.js"],
        finalUrl: "https://example.test/privacy/us",
        limitation: "click_only_no_post_window",
        newTrackerVendors: [],
        outcome: "navigated_to_policy_or_notice",
        pageUrl: "https://example.test/",
        pathObserved: true,
        persistedTrackerVendors: [],
        preferenceActionAttempted: false,
        preferenceActionCandidateCount: 0,
        preferenceActionCandidateLabels: [],
        preferenceActionConfirmed: null,
        preferenceActionLabel: null,
        preferenceActionLimitation: "no_preference_center_observed",
        preferenceCenterCategoryLabels: [],
        preferenceCenterObserved: false,
        preferenceCenterProbeAttempts: 1,
        preferenceCenterProbeErrorCategory: null,
        preferenceCenterProbeFinalUrl: "https://example.test/privacy/us",
        preferenceCenterProbeReason: "no_matching_controls_or_text",
        preferenceCenterProbeUrl: "https://example.test/privacy/us",
        preferenceCenterToggleCount: 0,
        preferenceCenterVisibleTextSnippets: ["Do not sell or share my personal information"],
        preferenceSaveAttempted: false,
        preferenceSaveCandidateCount: 0,
        preferenceSaveCandidateLabels: [],
        preferenceSaveConfirmed: null,
        preferenceSaveControlObserved: false,
        preferenceSaveLabel: null,
        preferenceToggleCandidateCount: 0,
        preferenceToggleCandidateLabels: [],
        removedTrackerVendors: ["Tealium"],
        saleShareToggleObserved: false,
        selectedLabel: "Do not sell or share my personal information",
        selectedUrl: "https://example.test/privacy/us",
        source: "cpra_ui",
        targetedAdvertisingToggleObserved: false,
        visibleTextSnippets: ["Do not sell or share my personal information"]
      },
      privacyChoiceLabels: ["Do not sell or share my personal information"],
      privacyChoiceUrls: ["https://example.test/privacy/us"],
      privacyControlAccessibilityIssueObserved: false,
      privacyControlAccessibilitySignals: [],
      privacyNoticeObserved: true,
      privacyNoticeSourceUrls: ["https://example.test/privacy"],
      privacyNoticeUrls: ["https://example.test/privacy"],
      saleShareRuntimeSignalsObserved: true,
      sensitivePiCategories: [],
      sensitivePiContextObserved: false,
      targetedAdvertisingSignalsObserved: true
    },
    cpraCbaOptOutEvidence: null,
    gpcVerification: {
      baselineThirdPartyCookieCount: 4,
      baselineTrackerCount: 1,
      evidenceUrls: ["https://example.test/privacy/us"],
      gpcRecognitionObserved: true,
      gpcSignalSent: true,
      gpcThirdPartyCookieCount: 1,
      gpcTrackerCount: 0,
      policyMentions: ["Global Privacy Control signals are honored."],
      status: "honored",
      thirdPartyCookieCountDelta: -3,
      trackerCountDelta: -1
    }
  },
  privacyChoiceProbeLimited: {
    contractVersion: CALIFORNIA_PRIVACY_RUNTIME_ARTIFACT_CONTRACT_VERSION,
    californiaPrivacyEvidence: {
      advertisingSharingVendors: ["TikTok Pixel"],
      collectionContextObserved: false,
      collectionContextUrls: [],
      collectionNoticeCueObserved: null,
      consumerRightsRequestMethodObserved: true,
      consumerRightsRequestMethodSnippets: ["Submit privacy requests through the privacy center."],
      consumerRightsRequestMethodTypes: ["privacy_portal"],
      consumerRightsRequestMethodUrls: ["https://example.test/privacy-center"],
      doNotSellShareLabels: ["Your Privacy Choices"],
      doNotSellSharePathLabel: "Your Privacy Choices",
      doNotSellSharePathObserved: true,
      doNotSellSharePathUrl: "https://example.test/privacy-center",
      doNotSellShareUrls: ["https://example.test/privacy-center"],
      evidenceRefs: ["runtime_artifact:california_privacy:privacy_choice_probe"],
      gpcRecognitionObserved: null,
      gpcSignalSent: true,
      gpcTestRan: true,
      gpcTrackingReductionObserved: null,
      limitUseSensitivePiPathLabel: null,
      limitUseSensitivePiPathObserved: null,
      limitUseSensitivePiPathUrl: null,
      optOutInteractionConfirmed: false,
      policyRuntimeDisclosureAlignment: "review",
      postOptOutTrackingPersisted: null,
      postOptOutTrackingReductionObserved: null,
      privacyChoiceInteractionEvidence: {
        afterThirdPartyCookieCount: 5,
        afterTrackerCount: 1,
        attempted: true,
        beforeThirdPartyCookieCount: 5,
        beforeTrackerCount: 1,
        clickAttempted: true,
        clickConfirmed: true,
        clickDepth: 1,
        evidenceRefs: ["california_privacy_choice_exercise", "privacy_choice_control_clicked"],
        evidenceUrls: ["https://analytics.example.test/pixel.js"],
        finalUrl: "https://example.test/privacy-center",
        limitation: "click_only_no_post_window",
        newTrackerVendors: [],
        outcome: "navigated_to_policy_or_notice",
        pageUrl: "https://example.test/",
        pathObserved: true,
        persistedTrackerVendors: ["TikTok Pixel"],
        preferenceActionAttempted: false,
        preferenceActionCandidateCount: 0,
        preferenceActionCandidateLabels: [],
        preferenceActionConfirmed: null,
        preferenceActionLabel: null,
        preferenceActionLimitation: "no_preference_center_observed",
        preferenceCenterCategoryLabels: [],
        preferenceCenterObserved: false,
        preferenceCenterProbeAttempts: 3,
        preferenceCenterProbeErrorCategory: "evaluate_failed",
        preferenceCenterProbeFinalUrl: "https://example.test/privacy-center",
        preferenceCenterProbeReason: "probe_error",
        preferenceCenterProbeUrl: "https://example.test/privacy-center",
        preferenceCenterToggleCount: 0,
        preferenceCenterVisibleTextSnippets: [],
        preferenceSaveAttempted: false,
        preferenceSaveCandidateCount: 0,
        preferenceSaveCandidateLabels: [],
        preferenceSaveConfirmed: null,
        preferenceSaveControlObserved: false,
        preferenceSaveLabel: null,
        preferenceToggleCandidateCount: 0,
        preferenceToggleCandidateLabels: [],
        removedTrackerVendors: [],
        saleShareToggleObserved: false,
        selectedLabel: "Your Privacy Choices",
        selectedUrl: "https://example.test/privacy-center",
        source: "cpra_ui",
        targetedAdvertisingToggleObserved: false,
        visibleTextSnippets: [
          "Opt-out of Sales/Interest-based Ads",
          "Opt-out of sales and sharing of information for interest-based ads."
        ]
      },
      privacyChoiceLabels: ["Your Privacy Choices"],
      privacyChoiceUrls: ["https://example.test/privacy-center"],
      privacyControlAccessibilityIssueObserved: false,
      privacyControlAccessibilitySignals: [],
      privacyNoticeObserved: true,
      privacyNoticeSourceUrls: ["https://example.test/privacy"],
      privacyNoticeUrls: ["https://example.test/privacy"],
      saleShareRequestUrls: ["https://analytics.example.test/pixel.js"],
      saleShareRuntimeSignalsObserved: true,
      sensitivePiCategories: [],
      sensitivePiContextObserved: false,
      targetedAdvertisingSignalsObserved: true
    },
    cpraCbaOptOutEvidence: null,
    gpcVerification: {
      baselineThirdPartyCookieCount: 5,
      baselineTrackerCount: 1,
      evidenceUrls: ["https://example.test/privacy-center"],
      gpcRecognitionObserved: null,
      gpcSignalSent: true,
      gpcThirdPartyCookieCount: 5,
      gpcTrackerCount: 1,
      policyMentions: [],
      status: "inconclusive",
      thirdPartyCookieCountDelta: 0,
      trackerCountDelta: 0
    }
  },
  sensitiveInputRuntimeSignal: {
    contractVersion: CALIFORNIA_PRIVACY_RUNTIME_ARTIFACT_CONTRACT_VERSION,
    californiaPrivacyEvidence: {
      advertisingSharingVendors: ["Amazon Ads", "Adobe Analytics"],
      californiaNoticeCueObserved: true,
      californiaNoticeCueText: "California residents may exercise privacy choices in the privacy notice.",
      collectionContextObserved: true,
      collectionContextTypes: ["search_form", "pre_submit_urlencoded"],
      collectionContextUrls: ["https://example.test/search"],
      collectionNoticeCueObserved: false,
      consumerRightsRequestMethodObserved: true,
      consumerRightsRequestMethodSnippets: ["Contact us to access, delete, or correct your information."],
      consumerRightsRequestMethodTypes: ["email", "web_form"],
      consumerRightsRequestMethodUrls: ["https://example.test/privacy/request"],
      doNotSellShareLabels: [],
      doNotSellSharePathLabel: null,
      doNotSellSharePathObserved: false,
      doNotSellSharePathUrl: null,
      doNotSellShareUrls: [],
      evidenceRefs: ["runtime_artifact:california_privacy:sensitive_surface"],
      gpcRecognitionObserved: false,
      gpcSignalSent: true,
      gpcTestRan: true,
      gpcTrackingReductionObserved: false,
      limitUseSensitivePiPathLabel: null,
      limitUseSensitivePiPathObserved: false,
      limitUseSensitivePiPathUrl: null,
      optOutInteractionConfirmed: null,
      policyRuntimeDisclosureAlignment: "gap_observed",
      policyRuntimeDisclosureSnippets: ["We disclose information to advertising and analytics partners."],
      postOptOutTrackingPersisted: null,
      postOptOutTrackingReductionObserved: null,
      privacyChoiceLabels: [],
      privacyChoiceUrls: [],
      privacyControlAccessibilityIssueObserved: null,
      privacyControlAccessibilitySignals: [],
      privacyNoticeObserved: true,
      privacyNoticeSourceUrls: ["https://example.test/privacy"],
      privacyNoticeUrls: ["https://example.test/privacy"],
      saleShareRequestUrls: ["https://aax.example.test/ad.js", "https://analytics.example.test/collect"],
      saleShareRuntimeSignalsObserved: true,
      sensitivePiCategories: ["health_information"],
      sensitivePiContextObserved: true,
      sensitivePiContextUrls: ["https://example.test/search?q=health"],
      sensitiveThirdPartyTrackingObserved: true,
      sensitiveThirdPartyTrackingRequestUrls: ["https://analytics.example.test/collect"],
      sensitiveThirdPartyTrackingVendors: ["Adobe Analytics"],
      targetedAdvertisingSignalsObserved: true,
      unmatchedRuntimeDisclosureVendors: ["Amazon Ads"]
    },
    cpraCbaOptOutEvidence: {
      advertisingSharingVendors: ["Amazon Ads", "Adobe Analytics"],
      cbaVendorTier1: ["aax.example.test"],
      cbaVendorTier2: [],
      choiceControlSearchScope: "homepage_footer_privacy_surfaces",
      choiceControlsInspected: true,
      cpraIconDetected: false,
      findingSeverity: "high",
      gpcCbaHonored: false,
      gpcOptOutDiscoveryAttemptUrls: ["https://example.test/privacy"],
      limitation: "homepage_only",
      optOutControlFound: false,
      optOutLinkHref: null,
      optOutLinkText: null,
      optOutUiResult: "absent",
      pageUrl: "https://example.test/",
      policyCbaLanguage: "legacy_do_not_sell",
      policyUiCongruent: false,
      privacyChoiceSearchUrls: ["https://example.test/privacy"],
      scanOriginGeo: "US-CA",
      suppressorApplied: null
    },
    gpcVerification: {
      baselineThirdPartyCookieCount: 6,
      baselineTrackerCount: 2,
      evidenceUrls: ["https://example.test/", "https://example.test/search"],
      gpcRecognitionObserved: false,
      gpcSignalSent: true,
      gpcThirdPartyCookieCount: 7,
      gpcTrackerCount: 3,
      policyMentions: ["We recognize browser privacy preference signals where required."],
      status: "ignored",
      thirdPartyCookieCountDelta: 1,
      trackerCountDelta: 1
    }
  }
} as const satisfies Record<string, CaliforniaPrivacyRuntimeArtifactContract>;
