import assert from "node:assert/strict";
import { test } from "node:test";
import {
  type CanonicalEvidenceBundle,
  type CookieEvent,
  type NetworkEvent,
  type NetworkResponseEvent,
  SCHEMA_VERSION,
  canonicalEvidenceBundleSchema,
} from "@certscore/contracts";
import { compactCanonicalEvidenceBundleForRetention } from "./index.js";
import { getScanProfile } from "./profiles.js";

test("canonical bundle retention keeps report-critical evidence under 400 KB excluding screenshots", () => {
  const bundle = oversizedGoogleLikeBundle();
  assert.ok(Buffer.byteLength(JSON.stringify(bundle)) > 400 * 1024);

  const compacted = compactCanonicalEvidenceBundleForRetention(bundle);
  const serializedBytes = Buffer.byteLength(JSON.stringify(compacted));

  assert.ok(serializedBytes <= 400 * 1024, `expected compacted bundle <= 400 KB, got ${serializedBytes} bytes`);
  assert.equal(compacted.runtimeCoverage?.coverageStatus, "usable");
  assert.equal(compacted.runtimeCoverage?.observationCounts.thirdPartyRequests, 3);
  assert.equal(compacted.runtimeCoverage?.observationCounts.cookieEvents, 8);
  assert.equal(compacted.derivedRuntimeSignals.preConsentTrackingObserved, true);
  assert.equal(compacted.derivedRuntimeSignals.thirdPartyCookiesPreConsentObserved, true);
  assert.equal(compacted.consentUiObservations[0]?.rejectControlObserved, true);
  assert.equal(compacted.policySurfaceObservations.map((surface) => surface.surfaceType).sort().join(","), "privacy_policy,terms");
  assert.ok(compacted.networkEvents.some((event) => event.thirdParty === true && event.cookieNamesSent.includes("NID")));
  assert.ok(compacted.cookieEvents.some((event) => event.cookieName === "NID"));
  assert.ok(compacted.observedJourneys.some((journey) => journey.journeyType === "cookie" && journey.displayName === "NID"));
  assert.equal(compacted.observedJourneys.some((journey) => journey.attributionStatus === "site_owned_infrastructure"), false);
});

function oversizedGoogleLikeBundle(): CanonicalEvidenceBundle {
  const startedAt = "2026-06-22T16:15:13.179Z";
  const networkEvents = Array.from({ length: 180 }, (_, index) => networkEvent(index));
  const networkResponseEvents = networkEvents.map((event, index) => networkResponseEvent(event, index));
  const cookieEvents = Array.from({ length: 8 }, (_, index) => cookieEvent(index));
  const observedJourneys: CanonicalEvidenceBundle["observedJourneys"] = [
    ...Array.from({ length: 160 }, (_, index) => lowSignalEndpointJourney(index)),
    {
      journeyId: "journey_cookie_nid",
      journeyType: "cookie",
      key: "cookie:nid",
      displayName: "NID",
      vendor: "Google",
      purpose: "advertising",
      sourceScanner: "pre_consent_runtime",
      scenariosObserved: ["fresh_pre_consent"],
      firstObservedAtMs: 950,
      lastObservedAtMs: 950,
      firstObservedConsentState: "pre_consent",
      consentStatesObserved: ["pre_consent"],
      firstPartyOrThirdParty: "third_party",
      entryPoint: "https://www.google.com/",
      entryPointSourceEventId: "cookie_0",
      relatedCookies: ["NID"],
      relatedScripts: [],
      relatedEndpoints: ["https://googleads.g.doubleclick.net/pagead/id"],
      relatedVendors: ["Google"],
      relatedVendorObservationIds: [],
      observedBehaviors: ["cookie_set"],
      eventRefs: [{
        eventId: "cookie_0",
        eventType: "cookie",
        timestampMs: 950,
        label: "NID",
        behavior: "cookie_set",
        thirdParty: true,
        scenario: "fresh_pre_consent",
        consentStateAtTime: "pre_consent",
      }],
      confidence: 0.9,
      directVsInferred: "direct",
      evidenceRefs: [{
        refId: "evidence_cookie_0",
        eventId: "cookie_0",
        eventType: "cookie",
        label: "NID cookie set before consent",
      }],
    },
    {
      journeyId: "journey_tracker_doubleclick",
      journeyType: "tracker",
      key: "tracker:doubleclick",
      displayName: "DoubleClick",
      vendor: "Google",
      purpose: "advertising",
      sourceScanner: "pre_consent_runtime",
      scenariosObserved: ["fresh_pre_consent"],
      firstObservedAtMs: 880,
      lastObservedAtMs: 880,
      firstObservedConsentState: "pre_consent",
      consentStatesObserved: ["pre_consent"],
      firstPartyOrThirdParty: "third_party",
      entryPoint: "https://googleads.g.doubleclick.net/pagead/id",
      entryPointSourceEventId: "net_0",
      relatedCookies: ["NID"],
      relatedScripts: [],
      relatedEndpoints: ["https://googleads.g.doubleclick.net/pagead/id"],
      relatedVendors: ["Google"],
      relatedVendorObservationIds: [],
      observedBehaviors: ["third_party_request_observed", "cookie_sent", "identifier_parameter_observed"],
      eventRefs: [{
        eventId: "net_0",
        eventType: "network_request",
        timestampMs: 880,
        url: "https://googleads.g.doubleclick.net/pagead/id",
        label: "DoubleClick request",
        behavior: "cookie_sent",
        thirdParty: true,
        scenario: "fresh_pre_consent",
        consentStateAtTime: "pre_consent",
      }],
      confidence: 0.86,
      directVsInferred: "direct",
      evidenceRefs: [{
        refId: "evidence_net_0",
        eventId: "net_0",
        eventType: "network_request",
        label: "DoubleClick request before consent",
      }],
    },
  ];

  return canonicalEvidenceBundleSchema.parse({
    scanId: "scan_google_like_large",
    url: "https://google.com/",
    normalizedUrl: "https://google.com/",
    startedAt,
    completedAt: "2026-06-22T16:15:19.634Z",
    region: "eu-west-1",
    scanProfile: getScanProfile("quick"),
    modulesRun: [{
      moduleName: "preConsentRuntimeScanner",
      status: "completed",
      startedAt,
      completedAt: "2026-06-22T16:15:17.319Z",
      durationMs: 4126,
      evidenceRefs: [],
      errors: [],
    }],
    runtimeTimeline: [...networkEvents, ...networkResponseEvents, ...cookieEvents],
    networkEvents,
    networkResponseEvents,
    cookieEvents,
    cookieSnapshots: [{
      artifactId: "cookies_pre_consent",
      capturedAtMs: 4100,
      consentStateAtTime: "pre_consent",
      cookies: cookieEvents.map((event) => ({
        name: event.cookieName,
        domain: event.cookieDomain ?? ".google.com",
        path: "/",
        sourceEventId: event.eventId,
      })),
      cookieNames: cookieEvents.map((event) => event.cookieName),
      evidenceRefs: [],
    }],
    storageSnapshots: [],
    scriptEvents: [],
    iframeEvents: [],
    consentUiObservations: [{
      observationId: "consent_ui_google",
      observedAtMs: 1700,
      likelyPresent: true,
      basis: ["control:reject_all:Reject all", "control:accept_all:Accept all"],
      textExcerpt: "Before you continue to Google",
      layerInspected: "first_layer",
      visibleChoiceLabels: ["Reject all", "Accept all"],
      acceptControlObserved: true,
      rejectControlObserved: true,
      managePreferencesControlObserved: true,
      controls: [
        { label: "Reject all", actionType: "reject_all", tagName: "button", selectorHint: "#W0wltc", visible: true },
        { label: "Accept all", actionType: "accept_all", tagName: "button", selectorHint: "#L2AGLb", visible: true },
      ],
      evidenceRefs: [{ refId: "consent_ui_ref", artifactId: "screenshot_pre", eventType: "consent_ui" }],
      confidence: 0.95,
      directVsInferred: "direct",
    }],
    collectionSurfaceObservations: [],
    consentInteractionEvents: [],
    policySurfaceObservations: [{
      observationId: "privacy_policy",
      surfaceType: "privacy_policy",
      url: "https://policies.google.com/privacy",
      normalizedUrl: "https://policies.google.com/privacy",
      discoveryMethod: "page_text_link",
      status: "fetched",
      textExcerpt: "Google Privacy Policy",
      evidenceRefs: [{ refId: "privacy_ref", url: "https://policies.google.com/privacy" }],
      artifactRefs: [{ artifactId: "privacy_artifact", artifactType: "json", path: "privacy.json", label: "Privacy policy" }],
      confidence: 0.95,
      directVsInferred: "direct",
    }, {
      observationId: "terms",
      surfaceType: "terms",
      url: "https://policies.google.com/terms",
      normalizedUrl: "https://policies.google.com/terms",
      discoveryMethod: "page_text_link",
      status: "fetched",
      textExcerpt: "Google Terms of Service",
      evidenceRefs: [{ refId: "terms_ref", url: "https://policies.google.com/terms" }],
      artifactRefs: [{ artifactId: "terms_artifact", artifactType: "json", path: "terms.json", label: "Terms" }],
      confidence: 0.95,
      directVsInferred: "direct",
    }],
    cmpRuntimeObservations: [],
    screenshots: [{
      artifactId: "screenshot_pre",
      path: "screenshot-pre-consent.png",
      url: "https://google.com/",
      capturedAtMs: 1800,
      pagePhase: "dom_content_loaded",
      consentStateAtTime: "pre_consent",
    }],
    domSnapshots: [],
    normalizedVendorObservations: [],
    observedJourneys,
    derivedRuntimeSignals: {
      thirdPartyVendorsObserved: false,
      preConsentTrackingObserved: true,
      thirdPartyCookiesPreConsentObserved: true,
      consentBannerLikelyPresent: true,
      sessionReplayOrBehavioralAnalyticsObserved: false,
      journeySummary: {
        journeyCount: observedJourneys.length,
        vendorJourneyCount: 0,
        productJourneyCount: 0,
        trackerJourneyCount: 1,
        cookieJourneyCount: 1,
        scriptJourneyCount: 0,
        endpointJourneyCount: 160,
        activeCollectionJourneyCount: 1,
        consentManagementJourneyCount: 0,
        notes: [],
      },
      notes: [],
    },
    runtimeCoverage: {
      coverageStatus: "usable",
      limitationKeys: [],
      fallbackModesUsed: [],
      observationCounts: {
        networkEvents: networkEvents.length,
        thirdPartyRequests: 3,
        cookieEvents: cookieEvents.length,
        cookiesBeforeConsent: 3,
        normalizedVendors: 0,
        observedJourneys: observedJourneys.length,
      },
      silentEmpty: false,
      notes: [],
    },
    artifactRefs: [{ artifactId: "screenshot_pre", artifactType: "screenshot", path: "screenshot-pre-consent.png", label: "Pre-consent screenshot" }],
    scannerVersion: "certscore-scan-core-v2-test",
    schemaVersion: SCHEMA_VERSION,
  });
}

function networkEvent(index: number): NetworkEvent {
  const thirdParty = index < 3;
  const hostname = thirdParty ? "googleads.g.doubleclick.net" : "www.google.com";
  return {
    eventId: `net_${index}`,
    eventType: "network_request",
    timestampMs: 800 + index,
    sourceScanner: "pre_consent_runtime",
    scenario: "fresh_pre_consent",
    consentStateAtTime: "pre_consent",
    pagePhase: "initial_navigation",
    url: `https://${hostname}/resource-${index}?client=abc123&id=${index}`,
    hostname,
    registrableDomain: thirdParty ? "doubleclick.net" : "google.com",
    firstParty: !thirdParty,
    thirdParty,
    topLevelUrl: "https://google.com/",
    initiatorStack: Array.from({ length: 12 }, (_, stackIndex) => `at googleBootstrap${stackIndex} (https://${hostname}/bundle-${index}.js:${stackIndex}:1)`),
    evidenceRefs: [],
    confidence: 0.95,
    directVsInferred: "direct",
    requestId: `req_${index}`,
    method: "GET",
    resourceType: index === 0 ? "fetch" : "script",
    requestUrl: `https://${hostname}/resource-${index}?client=abc123&id=${index}`,
    normalizedUrl: `https://${hostname}/resource-${index}`,
    requestHostname: hostname,
    path: `/resource-${index}`,
    queryParamNames: ["client", "id"],
    identifierParamNames: index === 0 ? ["id"] : [],
    advertisingClickIdParamNames: [],
    tagContainerParamNames: [],
    hasIdentifierLikeParameters: index === 0,
    hasAdvertisingClickIdParameters: false,
    hasTagContainerParameters: false,
    isMainFrame: index === 10,
    isSubFrame: false,
    isThirdParty: thirdParty,
    requestHeaders: {
      secFetchSite: thirdParty ? "cross-site" : "same-origin",
      cookieHeaderPresent: index === 0,
      cookieNames: index === 0 ? ["NID"] : [],
      authorizationHeaderPresent: false,
    },
    cookieHeaderPresent: index === 0,
    cookieNamesSent: index === 0 ? ["NID"] : [],
    authorizationHeaderPresent: false,
    collectionEndpointObserved: index === 0,
    endpointSubtype: thirdParty ? "google_ads_or_measurement" : "google_owned_infrastructure",
    attributionStatus: thirdParty ? "unresolved_meaningful" : "site_owned_infrastructure",
    attributionReason: thirdParty ? "third_party_identifier_request" : "google_owned_infrastructure",
    resolverBasis: [`hostname:${hostname}`, `path:/resource-${index}`, `resource_type:script`],
  };
}

function networkResponseEvent(request: NetworkEvent, index: number): NetworkResponseEvent {
  return {
    eventId: `resp_${index}`,
    eventType: "network_response",
    timestampMs: request.timestampMs + 50,
    sourceScanner: "pre_consent_runtime",
    scenario: "fresh_pre_consent",
    consentStateAtTime: "pre_consent",
    pagePhase: "initial_navigation",
    url: request.requestUrl,
    hostname: request.hostname,
    registrableDomain: request.registrableDomain,
    firstParty: request.firstParty,
    thirdParty: request.thirdParty,
    topLevelUrl: "https://google.com/",
    evidenceRefs: [],
    confidence: 0.95,
    directVsInferred: "direct",
    requestId: request.requestId,
    responseUrl: request.requestUrl,
    normalizedUrl: request.normalizedUrl,
    status: 200,
    contentType: "application/javascript",
    mimeType: "application/javascript",
    setCookieHeaders: index === 0 ? ["NID=redacted; Secure; SameSite=None"] : [],
    setCookieMetadata: index === 0 ? [{ name: "NID", domain: ".google.com", path: "/", secure: true, firstParty: false, thirdParty: true }] : [],
    cookieNamesSet: index === 0 ? ["NID"] : [],
    responseHeaders: { contentType: "application/javascript", cacheControl: "private, max-age=0", etagPresent: true },
    cacheHeaders: { cacheControl: "private, max-age=0", expires: "Mon, 22 Jun 2026 16:15:14 GMT" },
    accessControlHeaders: { accessControlAllowOrigin: "*" },
    timing: {
      startTime: index,
      domainLookupStart: index + 1,
      domainLookupEnd: index + 2,
      connectStart: index + 3,
      connectEnd: index + 4,
      requestStart: index + 5,
      responseStart: index + 6,
      responseEnd: index + 7,
    },
    sizes: { requestHeadersSize: 500, responseHeadersSize: 600, responseBodySize: 24000 },
  };
}

function cookieEvent(index: number): CookieEvent {
  const cookieName = index === 0 ? "NID" : `CONSENT_${index}`;
  return {
    eventId: `cookie_${index}`,
    eventType: "cookie",
    timestampMs: 950 + index,
    sourceScanner: "pre_consent_runtime",
    scenario: "fresh_pre_consent",
    consentStateAtTime: "pre_consent",
    pagePhase: "initial_navigation",
    url: "https://www.google.com/",
    hostname: "google.com",
    registrableDomain: "google.com",
    firstParty: index !== 0,
    thirdParty: index === 0,
    evidenceRefs: [],
    confidence: 0.95,
    directVsInferred: "direct",
    cookieName,
    cookieDomain: ".google.com",
    cookiePath: "/",
    secure: true,
    httpOnly: false,
    sourceRequestId: index === 0 ? "req_0" : undefined,
    sourceResponseEventId: index === 0 ? "resp_0" : undefined,
    cookieParty: index === 0 ? "third_party" : "first_party",
    vendorAssociated: false,
    cookiePurpose: index === 0 ? "advertising" : "consent_management",
    cookieClassificationBasis: [index === 0 ? "third_party" : "first_party", index === 0 ? "name:advertising" : "name:consent_management"],
    operation: "set_cookie_header",
    valueRedacted: true,
  };
}

function lowSignalEndpointJourney(index: number): CanonicalEvidenceBundle["observedJourneys"][number] {
  return {
    journeyId: `journey_infra_${index}`,
    journeyType: "endpoint",
    key: `endpoint:https://www.google.com/resource-${index}`,
    displayName: "www.google.com",
    sourceScanner: "pre_consent_runtime",
    scenariosObserved: ["fresh_pre_consent"],
    firstObservedAtMs: 800 + index,
    lastObservedAtMs: 800 + index,
    firstObservedConsentState: "pre_consent",
    consentStatesObserved: ["pre_consent"],
    firstPartyOrThirdParty: "first_party",
    entryPoint: `https://www.google.com/resource-${index}`,
    entryPointSourceEventId: `net_${Math.min(index + 3, 179)}`,
    relatedCookies: [],
    relatedScripts: [],
    relatedEndpoints: [`https://www.google.com/resource-${index}`],
    relatedVendors: [],
    relatedVendorObservationIds: [],
    observedBehaviors: [],
    endpointSubtype: "google_owned_infrastructure",
    attributionStatus: "site_owned_infrastructure",
    attributionReason: "google_owned_infrastructure",
    resolverBasis: [`hostname:www.google.com`, `path:/resource-${index}`, "resource_type:script", "google_endpoint_subtype:google_owned_infrastructure"],
    eventRefs: [{
      eventId: `net_${Math.min(index + 3, 179)}`,
      eventType: "network_request",
      timestampMs: 800 + index,
      url: `https://www.google.com/resource-${index}`,
      label: "Google infrastructure request",
      firstParty: true,
      thirdParty: false,
      scenario: "fresh_pre_consent",
      consentStateAtTime: "pre_consent",
    }],
    confidence: 0.52,
    directVsInferred: "inferred",
    evidenceRefs: [],
  };
}
