import type { MetadataRoute } from "next";
import { getFindingReferenceItems } from "../lib/marketing/finding-atlas";
import { SITE_URL } from "../lib/seo";

const staticPaths = [
  "",
  "/how-it-works",
  "/methodology",
  "/what-is-certscore",
  "/press",
  "/pricing",
  "/monitor-site",
  "/guides",
  "/regulatory",
  "/gdpr",
  "/ftc",
  "/accessibility",
  "/benchmarks",
  "/benchmarks/website-consent-tracking-2026",
  "/benchmarks/pre-consent-tracking-2026",
  "/benchmarks/session-replay-risk-2026",
  "/compare",
  "/compare/privacy-scanner-vs-cookie-scanner",
  "/compare/website-consent-audit-tools",
  "/compare/cmp-vs-runtime-consent-scanner",
  "/compare/cookiebot-alternative-runtime-testing",
  "/compare/onetrust-runtime-consent-testing",
  "/developers",
  "/developers/quickstart",
  "/developers/reference",
  "/developers/sdk",
  "/developers/mcp",
  "/developers/examples",
  "/api-pulse",
  "/api-pulse/agent",
  "/api-pulse-agent-guide.txt",
  "/llms.txt",
  "/llms-full.txt",
  "/.well-known/certscore-ai.json",
  "/.well-known/certscore-pulse",
  "/api/v1/openapi.json",
  "/api/v1/openapi.chatgpt.json",
  "/api/v2/health",
  "/api/v2/openapi.json",
  "/faq",
  "/contact",
  "/contact-sales",
  "/book-demo",
  "/sample-report",
  "/solutions",
  "/solutions/gdpr-website-compliance-scanner",
  "/solutions/cookie-consent-scanner",
  "/solutions/privacy-policy-risk-scanner",
  "/solutions/website-accessibility-compliance-scanner",
  "/terms",
  "/privacy",
  "/privacy-request",
  "/findings",
  "/guides/findings",
  "/guides/pre-consent-tracking",
  "/guides/pre-consent-tracking-detection",
  "/guides/cookie-consent-enforcement-checker",
  "/guides/detect-trackers-before-cookie-consent",
  "/guides/third-party-cookie-checker",
  "/guides/cmp-verification",
  "/guides/third-party-cookies-before-consent",
  "/guides/rtb-cookie-syncing",
  "/guides/session-replay-risk",
  "/guides/accessibility-homepage-signals",
  "/guides/check-website-tracking-before-consent",
  "/guides/check-third-party-cookies-before-consent",
  "/guides/website-consent-audit",
  "/guides/detect-tracking-before-consent",
  "/guides/reject-consent-tracking-test",
  "/guides/website-consent-audit-checklist",
  "/guides/privacy-scanner-vs-cookie-scanner",
  "/guides/website-fingerprinting",
  "/guides/website-scanning-basics",
  "/guides/disclosure-signals",
  "/guides/privacy-policy-signals",
  "/guides/ada-website-compliance",
  "/guides/cookie-consent-laws",
  "/guides/wcag-checklist",
  "/guides/wcag-website-checklist",
  "/guides/cookie-banner-requirements",
  "/guides/privacy-policy-examples",
  "/guides/website-disclosure-requirements",
  "/guides/website-privacy-policy-requirements",
  "/guides/website-signal-check",
  "/insights",
  "/insights/common-accessibility-issues",
  "/insights/common-cookie-consent-issues",
  "/insights/common-privacy-policy-gaps"
];

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();
  const findingPaths = getFindingReferenceItems().map((finding) => `/findings/${finding.id}`);

  return [...staticPaths, ...findingPaths].map((path) => ({
    url: `${SITE_URL}${path}`,
    lastModified: now
  }));
}
