import type { MetadataRoute } from "next";
import { getFindingReferenceItems } from "../lib/marketing/finding-atlas";
import { getPublishedReleases, releasePath } from "../lib/releases";
import { SITE_URL } from "../lib/seo";

const staticPaths = [
  "",
  "/how-it-works",
  "/methodology",
  "/what-is-certscore",
  "/press",
  "/pricing",
  "/monitor-site",
  "/guides",
  "/regulatory",
  "/gdpr",
  "/benchmarks",
  "/benchmarks/website-consent-tracking-2026",
  "/benchmarks/pre-consent-tracking-2026",
  "/benchmarks/session-replay-risk-2026",
  "/compare",
  "/compare/privacy-scanner-vs-cookie-scanner",
  "/compare/website-consent-audit-tools",
  "/compare/cmp-vs-runtime-consent-scanner",
  "/compare/cookiebot-alternative-runtime-testing",
  "/compare/onetrust-runtime-consent-testing",
  "/developers",
  "/developers/quickstart",
  "/developers/reference",
  "/developers/sdk",
  "/developers/mcp",
  "/mcp/light",
  "/releases",
  "/claude",
  "/developers/examples",
  "/faq",
  "/contact",
  "/contact-sales",
  "/book-demo",
  "/sample-report",
  "/browser-extension",
  "/browser-extension/privacy",
  "/solutions",
  "/solutions/gdpr-website-compliance-scanner",
  "/solutions/cookie-consent-scanner",
  "/solutions/privacy-policy-risk-scanner",
  "/terms",
  "/trust",
  "/security",
  "/privacy",
  "/privacy-request",
  "/findings",
  "/guides/findings",
  "/guides/pre-consent-tracking",
  "/guides/pre-consent-tracking-detection",
  "/guides/cookie-consent-enforcement-checker",
  "/guides/detect-trackers-before-cookie-consent",
  "/guides/third-party-cookie-checker",
  "/guides/cmp-verification",
  "/guides/third-party-cookies-before-consent",
  "/guides/rtb-cookie-syncing",
  "/guides/session-replay-risk",
  "/guides/check-website-tracking-before-consent",
  "/guides/check-third-party-cookies-before-consent",
  "/guides/website-consent-audit",
  "/guides/detect-tracking-before-consent",
  "/guides/reject-consent-tracking-test",
  "/guides/website-consent-audit-checklist",
  "/guides/privacy-scanner-vs-cookie-scanner",
  "/guides/website-fingerprinting",
  "/guides/website-scanning-basics",
  "/guides/disclosure-signals",
  "/guides/privacy-policy-signals",
  "/guides/cookie-consent-laws",
  "/guides/cookie-banner-requirements",
  "/guides/privacy-policy-examples",
  "/guides/website-disclosure-requirements",
  "/guides/website-privacy-policy-requirements",
  "/guides/website-signal-check",
  "/insights",
  "/insights/common-cookie-consent-issues",
  "/insights/common-privacy-policy-gaps"
];

export default function sitemap(): MetadataRoute.Sitemap {
  const findingPaths = getFindingReferenceItems().map((finding) => `/findings/${finding.id}`);
  const releasePaths = getPublishedReleases().map(releasePath);

  return [...staticPaths, ...releasePaths, ...findingPaths].map((path) => ({ url: `${SITE_URL}${path}` }));
}
