// Namespaced global stylesheet keeps report model tests independent of CSS loaders.
const styles = {
  explorer: "runtime-graph-explorer",
  toolbar: "runtime-graph-toolbar",
  tabs: "runtime-graph-tabs",
  tab: "runtime-graph-tab",
  scenario: "runtime-graph-scenario",
  coverage: "runtime-graph-coverage",
  legend: "runtime-graph-legend",
  layout: "runtime-graph-layout",
  list: "runtime-graph-list",
  card: "runtime-graph-card",
  brand: "runtime-graph-brand",
  name: "runtime-graph-name",
  time: "runtime-graph-time",
  meta: "runtime-graph-meta",
  node: "runtime-graph-node",
  children: "runtime-graph-children",
  expand: "runtime-graph-expand",
  edge: "runtime-graph-edge",
  inspector: "runtime-graph-inspector",
  eyebrow: "runtime-graph-eyebrow",
  title: "runtime-graph-title",
  subtitle: "runtime-graph-subtitle",
  group: "runtime-graph-group",
  hint: "runtime-graph-hint",
  fields: "runtime-graph-fields",
  source: "runtime-graph-source",
  footnote: "runtime-graph-footnote",
};
export default styles;
