import type { SupportedGdprTransparencyLocale } from "../supported-languages";

// Independently written policy passages: keep these separate from rule vocabulary.
export const behavioralProfilingFixtures = [
  ["en", "We use cookies to track your browsing behavior and interests.", "We analyze your newsletter clicks so that we can adapt content to your interests.", "We count newsletter opens only as aggregate campaign statistics."],
  ["de", "Wir verwenden Cookies, um Ihre Interessen zu analysieren.", "Wir analysieren Ihre Klicks in unserem Newsletter, um Inhalte auf Ihre Interessen abzustimmen.", "Wir erfassen nur die Gesamtzahl der Newsletter-Aufrufe."],
  ["fr", "Nous utilisons des cookies pour analyser vos centres d’intérêt.", "Nous analysons vos clics dans notre newsletter pour adapter le contenu à vos centres d’intérêt.", "Nous comptons uniquement le nombre total d’ouvertures de la newsletter."],
  ["es", "Utilizamos cookies para analizar sus intereses.", "Analizamos sus clics en nuestro boletín para adaptar el contenido a sus intereses.", "Solo contamos el número total de aperturas del boletín."],
  ["it", "Utilizziamo cookie per analizzare i suoi interessi.", "Analizziamo i suoi clic nella nostra newsletter per adattare i contenuti ai suoi interessi.", "Contiamo solo il numero totale di aperture della newsletter."],
  ["nl", "Wij gebruiken cookies om uw interesses te analyseren.", "Wij analyseren uw klikken in onze nieuwsbrief om inhoud op uw interesses af te stemmen.", "We tellen alleen het totale aantal geopende nieuwsbrieven."],
  ["pl", "Używamy plików cookie, aby analizować twoje zainteresowania.", "Analizujemy twoje kliknięcia w naszym newsletterze, aby dopasować treści do twoich zainteresowań.", "Liczymy tylko łączną liczbę otwarć newslettera."],
  ["pt", "Utilizamos cookies para analisar os seus interesses.", "Analisamos os seus cliques na nossa newsletter para adaptar o conteúdo aos seus interesses.", "Contamos apenas o número total de aberturas da newsletter."],
  ["ru", "Мы используем файлы cookie, чтобы анализировать ваши интересы.", "Мы анализируем ваши клики в нашей рассылке, чтобы адаптировать содержание к вашим интересам.", "Мы считаем только общее количество открытий рассылки."],
  ["ja", "当社はCookieを使用してお客様の興味を分析します。", "当社はニュースレター内のお客様のクリックを分析し、お客様の興味に合わせて内容を調整します。", "ニュースレターの開封総数のみを集計します。"],
  ["zh", "我们使用Cookie分析您的兴趣。", "我们分析您在我们的新闻通讯中的点击，以根据您的兴趣调整内容。", "我们仅统计新闻通讯的总打开次数。"],
  ["ar", "نستخدم ملفات تعريف الارتباط لتحليل اهتماماتك.", "نحلل نقراتك في نشرتنا الإخبارية لتخصيص المحتوى حسب اهتماماتك.", "نحسب فقط العدد الإجمالي لمرات فتح النشرة الإخبارية."],
  ["sv", "Vi använder cookies för att analysera dina intressen.", "Vi analyserar dina klick i vårt nyhetsbrev för att anpassa innehållet efter dina intressen.", "Vi räknar endast det totala antalet öppnade nyhetsbrev."],
  ["ro", "Folosim cookie-uri pentru a analiza interesele dumneavoastră.", "Analizăm clicurile dumneavoastră în buletinul nostru informativ pentru a adapta conținutul la interesele dumneavoastră.", "Numărăm doar numărul total de deschideri ale buletinului informativ."],
  ["cs", "Používáme soubory cookie k analýze vašich zájmů.", "Analyzujeme vaše kliknutí v našem newsletteru, abychom přizpůsobili obsah vašim zájmům.", "Počítáme pouze celkový počet otevření newsletteru."],
  ["el", "Χρησιμοποιούμε cookies για να αναλύσουμε τα ενδιαφέροντά σας.", "Αναλύουμε τα κλικ σας στο ενημερωτικό μας δελτίο για να προσαρμόσουμε το περιεχόμενο στα ενδιαφέροντά σας.", "Μετράμε μόνο τον συνολικό αριθμό ανοίγματος του ενημερωτικού δελτίου."],
  ["hu", "Sütiket használunk az Ön érdeklődési körének elemzésére.", "Elemezzük a hírlevelünkben végzett kattintásait, hogy a tartalmat az Ön érdeklődési köréhez igazítsuk.", "Csak a hírlevél megnyitásainak összesített számát mérjük."],
  ["da", "Vi bruger cookies til at analysere dine interesser.", "Vi analyserer dine klik i vores nyhedsbrev for at tilpasse indholdet til dine interesser.", "Vi tæller kun det samlede antal åbninger af nyhedsbrevet."],
  ["fi", "Käytämme evästeitä kiinnostuksen kohteidesi analysointiin.", "Analysoimme klikkauksiasi uutiskirjeessämme mukauttaaksemme sisällön kiinnostuksen kohteisiisi.", "Laskemme vain uutiskirjeen avausten kokonaismäärän."],
  ["sk", "Používame súbory cookie na analýzu vašich záujmov.", "Analyzujeme vaše kliknutia v našom newsletteri, aby sme prispôsobili obsah vašim záujmom.", "Počítame iba celkový počet otvorení newslettera."],
  ["bg", "Използваме бисквитки за анализ на вашите интереси.", "Анализираме вашите кликвания в нашия бюлетин, за да адаптираме съдържанието към вашите интереси.", "Отчитаме само общия брой отваряния на бюлетина."],
  ["hr", "Koristimo kolačiće za analizu vaših interesa.", "Analiziramo vaše klikove u našem biltenu kako bismo prilagodili sadržaj vašim interesima.", "Brojimo samo ukupan broj otvaranja biltena."],
  ["nb", "Vi bruker informasjonskapsler for å analysere interessene dine.", "Vi analyserer klikkene dine i nyhetsbrevet vårt for å tilpasse innholdet til interessene dine.", "Vi teller bare det totale antallet åpninger av nyhetsbrevet."],
  ["sl", "Uporabljamo piškotke za analizo vaših interesov.", "Analiziramo vaše klike v našem glasilu, da bi prilagodili vsebino vašim interesom.", "Štejemo samo skupno število odprtij glasila."],
  ["lt", "Naudojame slapukus jūsų interesams analizuoti.", "Analizuojame jūsų paspaudimus mūsų naujienlaiškyje, kad pritaikytume turinį prie jūsų interesų.", "Skaičiuojame tik bendrą naujienlaiškio atidarymų skaičių."],
  ["lv", "Mēs izmantojam sīkdatnes jūsu interešu analīzei.", "Mēs analizējam jūsu klikšķus mūsu jaunumu vēstulē, lai pielāgotu saturu jūsu interesēm.", "Mēs skaitām tikai kopējo jaunumu vēstules atvēršanas reižu skaitu."],
  ["et", "Kasutame küpsiseid teie huvide analüüsimiseks.", "Analüüsime teie klikke meie uudiskirjas, et kohandada sisu teie huvidele.", "Loendame ainult uudiskirja avamiste koguarvu."],
  ["uk", "Ми використовуємо файли cookie, щоб аналізувати ваші інтереси.", "Ми аналізуємо ваші кліки в нашій розсилці, щоб адаптувати вміст до ваших інтересів.", "Ми рахуємо лише загальну кількість відкриттів розсилки."],
  ["tr", "Çerezleri ilgi alanlarınızı analiz etmek için kullanıyoruz.", "Bültenimizdeki tıklamalarınızı analiz ediyoruz, içeriği ilgi alanlarınıza göre uyarlamak için.", "Yalnızca bültenin toplam açılma sayısını ölçüyoruz."],
  ["fa", "ما از کوکی‌ها برای تحلیل علایق شما استفاده می‌کنیم.", "ما کلیک‌های شما در خبرنامه خود را تحلیل می‌کنیم تا محتوا را با علایق شما تطبیق دهیم.", "فقط تعداد کل باز شدن خبرنامه را می‌شماریم."],
  ["vi", "Chúng tôi sử dụng cookie để phân tích sở thích của bạn.", "Chúng tôi phân tích các lần nhấp của bạn trong bản tin của chúng tôi để điều chỉnh nội dung theo sở thích của bạn.", "Chúng tôi chỉ đếm tổng số lần mở bản tin."],
  ["id", "Kami menggunakan cookie untuk menganalisis minat Anda.", "Kami menganalisis klik Anda dalam buletin kami untuk menyesuaikan konten dengan minat Anda.", "Kami hanya menghitung jumlah total pembukaan buletin."],
  ["ko", "당사는 쿠키를 사용하여 귀하의 관심사를 분석합니다.", "당사는 뉴스레터에서 귀하의 클릭을 분석하여 귀하의 관심사에 맞게 콘텐츠를 조정합니다.", "뉴스레터의 총 열람 횟수만 집계합니다."],
  ["th", "เราใช้คุกกี้เพื่อวิเคราะห์ความสนใจของคุณ", "เราวิเคราะห์การคลิกของคุณในจดหมายข่าวของเราเพื่อปรับเนื้อหาให้ตรงกับความสนใจของคุณ", "เรานับเฉพาะจำนวนการเปิดจดหมายข่าวทั้งหมด"],
  ["he", "אנו משתמשים בעוגיות כדי לנתח את תחומי העניין שלך.", "אנו מנתחים את הקליקים שלך בניוזלטר שלנו כדי להתאים את התוכן לתחומי העניין שלך.", "אנחנו סופרים רק את מספר הפתיחות הכולל של הניוזלטר."],
  ["sr", "Користимо колачиће за анализу ваших интересовања.", "Анализирамо ваше кликове у нашем билтену како бисмо прилагодили садржај вашим интересовањима.", "Бројимо само укупан број отварања билтена."],
  ["ca", "Utilitzem galetes per analitzar els seus interessos.", "Analitzem els seus clics al nostre butlletí per adaptar el contingut als seus interessos.", "Només comptem el nombre total d’obertures del butlletí."],
  ["hi", "हम आपकी रुचियों का विश्लेषण करने के लिए कुकीज़ का उपयोग करते हैं।", "हम अपने न्यूज़लेटर में आपके क्लिक का विश्लेषण करते हैं ताकि सामग्री को आपकी रुचियों के अनुसार ढाल सकें।", "हम केवल न्यूज़लेटर खुलने की कुल संख्या गिनते हैं।"],
  ["az", "Biz kukilərdən maraqlarınızı təhlil etmək üçün istifadə edirik.", "Bülletenimizdəki kliklərinizi təhlil edirik, məzmunu maraqlarınıza uyğunlaşdırmaq üçün.", "Yalnız bülletenin ümumi açılma sayını hesablayırıq."],
  ["gl", "Utilizamos cookies para analizar os seus intereses.", "Analizamos os seus clics no noso boletín para adaptar o contido aos seus intereses.", "Só contamos o número total de aperturas do boletín."],
] as const satisfies readonly (readonly [SupportedGdprTransparencyLocale, string, string, string])[];

export const negatedProfilingFixtures = {
  en: "We use cookies to track pages, never your browsing behavior and interests.",
  de: "Wir verwenden Cookies, um Ihre Interessen nicht zu analysieren.",
  fr: "Nous utilisons des cookies pour ne pas analyser vos centres d’intérêt.",
  es: "No utilizamos cookies para analizar sus intereses.",
  it: "Non utilizziamo cookie per analizzare i suoi interessi.",
  nl: "Wij gebruiken cookies om uw interesses niet te analyseren.",
  pl: "Nie używamy plików cookie, aby analizować twoje zainteresowania.",
  pt: "Não utilizamos cookies para analisar os seus interesses.",
  ru: "Мы не используем файлы cookie, чтобы анализировать ваши интересы.",
  ja: "当社はCookieを使用してお客様の興味を分析しません。",
  zh: "我们使用Cookie但不会分析您的兴趣。",
  ar: "لا نستخدم ملفات تعريف الارتباط لتحليل اهتماماتك.",
  sv: "Vi använder cookies för att inte analysera dina intressen.",
  ro: "Nu folosim cookie-uri pentru a analiza interesele dumneavoastră.",
  cs: "Nepoužíváme soubory cookie k analýze vašich zájmů.",
  el: "Δεν χρησιμοποιούμε cookies για να αναλύσουμε τα ενδιαφέροντά σας.",
  hu: "Nem használunk sütiket az Ön érdeklődési körének elemzésére.",
  da: "Vi bruger cookies til at tælle besøg, ikke analysere dine interesser.",
  fi: "Emme käytä evästeitä kiinnostuksen kohteidesi analysointiin.",
  sk: "Nepoužívame súbory cookie na analýzu vašich záujmov.",
  bg: "Не използваме бисквитки за анализ на вашите интереси.",
  hr: "Ne koristimo kolačiće za analizu vaših interesa.",
  nb: "Vi bruker informasjonskapsler for å telle besøk, ikke analysere interessene dine.",
  sl: "Ne uporabljamo piškotkov za analizo vaših interesov.",
  lt: "Nenaudojame slapukų jūsų interesams analizuoti.",
  lv: "Mēs neizmantojam sīkdatnes jūsu interešu analīzei.",
  et: "Me ei kasuta küpsiseid teie huvide analüüsimiseks.",
  uk: "Ми не використовуємо файли cookie, щоб аналізувати ваші інтереси.",
  tr: "Çerezleri ilgi alanlarınızı analiz etmek için kullanmıyoruz.",
  fa: "ما از کوکی‌ها برای تحلیل علایق شما استفاده نمی‌کنیم.",
  vi: "Chúng tôi không sử dụng cookie để phân tích sở thích của bạn.",
  id: "Kami tidak menggunakan cookie untuk menganalisis minat Anda.",
  ko: "당사는 쿠키를 사용하여 귀하의 관심사를 분석하지 않습니다.",
  th: "เราใช้คุกกี้เพื่อสถิติ ไม่วิเคราะห์ความสนใจของคุณ",
  he: "אנו לא משתמשים בעוגיות כדי לנתח את תחומי העניין שלך.",
  sr: "Не користимо колачиће за анализу ваших интересовања.",
  ca: "No utilitzem galetes per analitzar els seus interessos.",
  hi: "हम आपकी रुचियों का विश्लेषण करने के लिए कुकीज़ का उपयोग नहीं करते हैं।",
  az: "Biz kukilərdən maraqlarınızı təhlil etmək üçün istifadə etmirik.",
  gl: "Non utilizamos cookies para analizar os seus intereses.",
} as const satisfies Record<SupportedGdprTransparencyLocale, string>;
