alter table public.scan_snapshots
  add column if not exists dark_pattern_reject_button_missing boolean not null default false,
  add column if not exists dark_pattern_accept_button_prominence boolean not null default false,
  add column if not exists dark_pattern_forced_consent_wall boolean not null default false,
  add column if not exists dark_pattern_accept_only_banner boolean not null default false,
  add column if not exists dark_pattern_dismiss_without_reject boolean not null default false,
  add column if not exists dark_pattern_countdown_timer_present boolean not null default false,
  add column if not exists dark_pattern_fake_scarcity_language boolean not null default false,
  add column if not exists form_collects_ssn boolean not null default false,
  add column if not exists form_collects_government_id boolean not null default false,
  add column if not exists form_collects_health_information boolean not null default false,
  add column if not exists form_collects_financial_information boolean not null default false,
  add column if not exists form_collects_birthdate boolean not null default false,
  add column if not exists form_collects_geolocation boolean not null default false,
  add column if not exists auto_renew_disclosure_present boolean not null default false,
  add column if not exists subscription_cancellation_policy_present boolean not null default false,
  add column if not exists ad_network_google_ads boolean not null default false,
  add column if not exists ad_network_meta_ads boolean not null default false,
  add column if not exists retargeting_pixel_detected boolean not null default false,
  add column if not exists session_replay_tool_detected boolean not null default false,
  add column if not exists ai_chatbot_present boolean not null default false,
  add column if not exists ai_chatbot_vendor text,
  add column if not exists ai_assistant_widget_detected boolean not null default false,
  add column if not exists vulnerability_disclosure_page_present boolean not null default false,
  add column if not exists trust_center_present boolean not null default false,
  add column if not exists incident_status_page_present boolean not null default false;
