import assert from "node:assert/strict";
import { chromium } from "playwright";
import { runtimeGraphUiFixture } from "../apps/web/components/scans/runtime-evidence-graph-ui-fixture";

// Explicit local development check; never visits production or creates a database scan.
async function main() {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1280, height: 1000 } });
  const errors: string[] = []; page.on("pageerror", error => errors.push(error.message));
  await page.route("**/api/operational-events", route => route.fulfill({ status: 200, json: { ok: true } }));
  const projection = { ...runtimeGraphUiFixture(), scanId: "00000000-0000-4000-8000-000000000123" };
  let reads = 0; let responseMode: "success" | "limit" | "corrupt" = "success";
  await page.route(`http://localhost:3000/api/scans/${projection.scanId}/runtime-evidence-graph`, async route => {
    reads++;
    if (responseMode === "limit") return route.fulfill({ status: 429, headers: { "Retry-After": "60" }, json: { error: "Synthetic canonical quota denial" } });
    return route.fulfill({ json: responseMode === "corrupt" ? { ...projection, scanId: "foreign" } : projection });
  });
  try {
    await page.goto("http://localhost:3000/dev-fixtures/runtime-evidence-graph?lazy=1", { waitUntil: "networkidle" });
    assert.equal(reads, 0, "collapsed inventory must not fetch graph bytes");
    assert.equal(await page.getByTestId("runtime-graph-disabled-fixture").getByTestId("runtime-evidence-graph").count(), 0, "disabled presentation must not leave an empty graph tile");
    await page.getByText("This scan has no verified, publishable relationship graph. Existing observations remain available. Missing graph evidence does not establish absence.", { exact: true }).waitFor();
    assert.equal(reads, 0, "explicit historical unavailability never requests artifact bytes");
    const summary = page.getByText("Explore cookies & trackers 4 captured scenarios", { exact: true });
    await summary.focus(); await summary.press("Enter");
    await page.getByLabel("Find an item").waitFor();
    assert.equal(reads, 1);
    await page.getByRole("button", { name: "Measurement request", exact: false }).click();
    await page.getByText("Parents and sources 2", { exact: true }).click();
    await page.getByRole("button", { name: "Widget script Initiating script", exact: false }).click();
    await page.getByRole("heading", { name: "Widget script", exact: true }).waitFor();
    await page.getByLabel("Find an item").fill("fixture_key_44");
    assert.equal(await page.getByRole("list", { name: "Captured evidence nodes" }).getByRole("button").count(), 1);
    await page.getByLabel("Scenario", { exact: true }).first().selectOption("post_reject");
    await page.getByRole("button", { name: "fixture_key_44", exact: false }).click();
    await page.getByText("Across scenarios", { exact: true }).waitFor();
    await page.locator("aside summary").filter({ hasText: "All retained fields" }).click();
    await page.getByLabel("Find a field").fill("observedAtMs");
    await page.getByLabel("Exact field names").check();
    await page.getByText("node.observedAtMs", { exact: true }).waitFor();
    await page.getByText("Safe JSON", { exact: true }).click();
    assert.equal((await page.getByRole("button", { name: "Copy safe evidence JSON" }).innerText()).trim(), "", "copy is icon-only");
    assert.equal(reads, 1, "scenario/search/detail navigation reuses one verified graph");
    await summary.click(); await summary.click(); assert.equal(reads, 1);

    responseMode = "limit";
    await page.reload({ waitUntil: "networkidle" });
    await summary.click();
    await page.getByText("Read limit reached. Wait 60 seconds before retrying.", { exact: true }).waitFor();
    const limitedReads = reads;
    await page.waitForTimeout(250); assert.equal(reads, limitedReads, "no automatic quota retry");
    responseMode = "success"; await page.getByRole("button", { name: "Retry loading evidence" }).click();
    await page.getByLabel("Find an item").waitFor(); assert.equal(reads, limitedReads + 1);

    responseMode = "corrupt";
    await page.reload({ waitUntil: "networkidle" });
    await summary.click();
    await page.getByText("The retained relationship evidence did not verify.", { exact: true }).waitFor();
    assert.equal(await page.getByLabel("Find an item").count(), 0);
    await page.goto("http://localhost:3000/dev-fixtures/runtime-evidence-graph", { waitUntil: "networkidle" });
    await page.getByRole("button", { name: "Inventory", exact: true }).click();
    await page.getByText("Pre-consent inventory. In a scan report, this tab preserves the existing full table, charts, detail controls and export.", { exact: true }).waitFor();
    await page.getByRole("button", { name: "Relationships", exact: true }).first().click();
    if (await page.getByRole("button", { name: "Reject analytics", exact: true }).isVisible()) await page.getByRole("button", { name: "Reject analytics", exact: true }).click();
    await page.locator('[data-node-id="request"]').click();
    await page.screenshot({ path: "/tmp/runtime-evidence-layout-desktop.png", fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false, "no mobile horizontal overflow");
    await page.screenshot({ path: "/tmp/runtime-evidence-layout-mobile.png", fullPage: true });
    await page.setViewportSize({ width: 1280, height: 1000 });
    await page.goto("http://localhost:3000/dev-fixtures/runtime-evidence-graph?report=1", { waitUntil: "networkidle" });
    const table = page.locator("#preconsent-inventory-table");
    await table.waitFor();
    assert.equal(await table.locator(":scope > thead th").count(), 14);
    assert.equal(await table.locator(":scope > tbody > [data-inventory-row]").count(), 3);
    const first = table.locator('[data-inventory-row]').first();
    await first.getByRole("button", { name: "+ 2 sources", exact: true }).click();
    await page.getByRole("button", { name: "+ 1 child", exact: true }).first().click();
    await page.getByRole("button", { name: /Measurement response/ }).waitFor();
    await page.getByRole("button", { name: "Sort by Vendor" }).click();
    assert.equal(await table.evaluate(element => Array.from(element.querySelectorAll(':scope > tbody > [data-inventory-row]')).every(row => row.nextElementSibling?.getAttribute('data-resource-detail') === row.getAttribute('data-resource-owner'))), true, "sorting retains each expanded companion with its owner");
    await page.screenshot({ path: "/tmp/runtime-evidence-report-desktop.png", fullPage: true });
    await page.getByLabel("Resource evidence scenario").selectOption("post_accept");
    await page.getByText("Inventory columns describe pre-consent observations.", { exact: false }).first().waitFor();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.getByLabel("Cookies and trackers mobile list").waitFor();
    await page.getByLabel("Cookies and trackers mobile list").locator("summary").filter({ hasText: "Relationships & resource details" }).first().click();
    assert.ok((await page.getByLabel("Cookies and trackers mobile list").boundingBox())!.width < 390, "mobile details must not widen the inventory");
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false);
    await page.screenshot({ path: "/tmp/runtime-evidence-report-mobile.png", fullPage: true });
    await page.setViewportSize({ width: 1280, height: 1000 });
    const beforeTableReads = reads;
    await page.goto("http://localhost:3000/dev-fixtures/runtime-evidence-graph?report=1&lazy=1", { waitUntil: "networkidle" });
    assert.equal(reads, beforeTableReads, "table does not fetch until resource expansion");
    responseMode = "success";
    await table.locator('[data-inventory-row]').first().getByRole("button", { name: "+ Details", exact: true }).click();
    await page.getByRole("button", { name: /Measurement request/ }).waitFor();
    assert.equal(reads, beforeTableReads + 1);
    await table.locator('[data-inventory-row]').nth(1).getByRole("button", { name: "+ 1 source", exact: true }).click();
    assert.equal(reads, beforeTableReads + 1, "all row disclosures share one verified read");
    responseMode = "corrupt";
    await page.reload({ waitUntil: "networkidle" });
    await table.locator('[data-inventory-row]').first().getByRole("button", { name: "+ Details", exact: true }).click();
    await page.getByText("The retained relationship evidence did not verify.", { exact: false }).waitFor();
    assert.deepEqual(errors, []);
    console.info(JSON.stringify({ result: "passed", syntheticApiReads: reads, checks: ["disabled_no_tile", "historical_no_reads", "lazy_zero_reads", "keyboard", "multiple_parents", "search", "scenario", "evidence_drawer", "single_fetch", "429_no_auto_retry", "explicit_retry", "cross_scan_rejected", "icon_only_copy", "actual_report_inventory", "classification_scope", "desktop_mobile", "no_page_errors"], limitation: "API responses intercepted with synthetic data; separate server storage/auth/quota tests cover the real read boundary" }));
  } finally { await browser.close(); }
}
void main().catch(error => { console.error(error); process.exitCode = 1; });
