import { readFile, writeFile } from "node:fs/promises";
import { gpcBoundedObservationSchema } from "../packages/certscore-contracts/src/gpc-bounded-observation";
import { z } from "zod";
// One canonical schema; public packages remain standalone and contain no private runtime dependency.
async function main() {
const source = await readFile("packages/certscore-contracts/src/gpc-bounded-observation.ts", "utf8");
const banner = "// Generated by scripts/sync-gpc-observation-contract.ts; do not edit.\n";
function project(schema: z.ZodTypeAny): { ts: string; json: any } {
  if (schema instanceof z.ZodEffects) return project(schema.innerType());
  if (schema instanceof z.ZodNullable) { const p = project(schema.unwrap()); return { ts: `${p.ts} | null`, json: { anyOf: [p.json, { type: "null" }] } }; }
  if (schema instanceof z.ZodLiteral) return { ts: JSON.stringify(schema.value), json: { const: schema.value, type: typeof schema.value } };
  if (schema instanceof z.ZodEnum) return { ts: schema.options.map((v: string) => JSON.stringify(v)).join(" | "), json: { type: "string", enum: schema.options } };
  if (schema instanceof z.ZodBoolean) return { ts: "boolean", json: { type: "boolean" } };
  if (schema instanceof z.ZodNumber) return { ts: "number", json: { type: "integer", minimum: 0 } };
  if (schema instanceof z.ZodString) return { ts: "string", json: { type: "string", ...Object.fromEntries(schema._def.checks.flatMap(c => c.kind === "min" ? [["minLength", c.value]] : c.kind === "max" ? [["maxLength", c.value]] : c.kind === "regex" ? [["pattern", c.regex.source]] : [])) } };
  if (schema instanceof z.ZodArray) { const p = project(schema.element); return { ts: `Array<${p.ts}>`, json: { type: "array", items: p.json, ...(schema._def.maxLength ? { maxItems: schema._def.maxLength.value } : {}) } }; }
  if (schema instanceof z.ZodObject) {
    const entries = Object.entries(schema.shape).map(([key, value]) => [key, project(value as z.ZodTypeAny)] as const);
    return { ts: `{ ${entries.map(([key,p]) => `${key}: ${p.ts};`).join(" ")} }`, json: { type: "object", additionalProperties: false, required: entries.map(([key]) => key), properties: Object.fromEntries(entries.map(([key,p]) => [key,p.json])) } };
  }
  throw Error(`Unsupported schema type ${schema._def.typeName}`);
}
const projected = project(gpcBoundedObservationSchema);
const files = {
  "packages/certscore-api-contracts/src/gpc-bounded-observation.ts": banner + source.split("\nexport function describeGpcBoundedObservation")[0]!.trimEnd() + "\n",
  "packages/certscore-api-contracts/src/gpc-bounded-observation-openapi.ts": banner + `export const gpcBoundedObservationOpenApi = ${JSON.stringify(projected.json, null, 2)} as const;\n`,
  "packages/certscore-sdk/src/gpc-bounded-observation.ts": banner + `export type GpcBoundedObservation = ${projected.ts};\n`,
};
for (const [file, contents] of Object.entries(files)) {
  if (process.argv.includes("--check")) { if (await readFile(file, "utf8") !== contents) throw Error(`Generated contract drift: ${file}`); }
  else await writeFile(file, contents);
}

}
void main();
