import assert from "node:assert/strict";
import test from "node:test";
import { projectSnapshotSignals } from "./project-snapshot-signals";
import type { ScanSnapshot } from "../types/snapshots";

function buildSnapshot(overrides: Partial<ScanSnapshot> = {}): ScanSnapshot {
  return {
    organizationId: null,
    domainId: null,
    scanId: null,
    domain: "example.com",
    normalizedUrl: "https://example.com/",
    finalUrl: "https://example.com/",
    registeredDomain: "example.com",
    siteName: null,
    pageTitle: null,
    scanTimestamp: "2026-04-18T18:37:07.114Z",
    scanStatus: "completed",
    scanType: "preview",
    pagesRequested: 1,
    pagesScanned: 0,
    partialScan: true,
    highestSuccessfulTier: null,
    stopTier: null,
    stopReason: null,
    stopReasonCode: null,
    accessPostureClass: null,
    blockedFlag: false,
    captchaFlag: false,
    authWallDetected: false,
    authWallSuspected: false,
    challengeSuspected: false,
    rateLimitSuspected: false,
    geoBlockSuspected: false,
    fingerprintBlockSuspected: false,
    homepageFetchStatus: "ok",
    homepageFetchHttpStatus: 200,
    robotsAllowed: true,
    robotsFetchStatus: "ok",
    robotsFetchHttpStatus: 200,
    blockPageClassification: null,
    blockVendorGuess: null,
    egressId: null,
    normalizedBodyHash: null,
    passiveVerificationAttemptCount: 0,
    passiveVerificationAttempted: false,
    coverageLevel: null,
    privacyPolicyPresent: true,
    termsOfServicePresent: true,
    cookiePolicyPresent: false,
    accessibilityStatementPresent: false,
    refundPolicyPresent: false,
    cancellationPolicyPresent: false,
    contactPagePresent: false,
    privacyContactMethodPresent: false,
    privacyContactChannelType: "none",
    privacyEmailSpecificPresent: false,
    privacyRequestFormPresent: false,
    dsarRequestMechanismPresent: false,
    dataAccessRequestPresent: false,
    dataDeletionRequestPresent: false,
    supervisoryAuthorityReferencePresent: false,
    mobileAppLinksDetected: false,
    performanceClaimPresent: false,
    performanceClaimCount: 0,
    returnOrYieldPercentagePresent: false,
    outperformanceClaimPresent: false,
    benchmarkComparisonPresent: false,
    hypotheticalResultsDisclaimerPresent: false,
    feeDisclosurePresent: false,
    aprDisclosurePresent: false,
    subscriptionOfferDetected: false,
    freeTrialDetected: false,
    negativeOptionFeaturePresent: false,
    continuityDisclosurePresent: false,
    trialConversionDisclosurePresent: false,
    urgencyOrScarcityLanguagePresent: false,
    scarcityClaimCount: 0,
    testimonialOrReviewPresent: false,
    testimonialOrReviewDisclosurePresent: false,
    affiliateDisclosurePresent: false,
    advertisingDisclosurePresent: false,
    kidDirectedContentDetected: false,
    childrenAudienceLikely: false,
    childrenPrivacyDisclosurePresent: false,
    mentionsChildrenPrivacyPractices: false,
    mentionsGdpr: false,
    mentionsCcpaOrCpra: false,
    mentionsCrossBorderTransfer: false,
    mentionsSubprocessorsOrVendors: false,
    mentionsAutomatedDecisioning: false,
    mentionsAiUsage: false,
    mentionsDataSaleOrSharing: false,
    mentionsSensitiveData: false,
    mentionsBiometricData: false,
    mentionsHealthData: false,
    mentionsFinancialData: false,
    mentionsLocationData: false,
    mentionsDataRetention: false,
    dataRetentionSpecificPeriodDetected: null,
    crossBorderTransferMechanismDetected: null,
    doubleOptInReferencePresent: null,
    thirdPartyDisclosureSpecificity: null,
    cookieBannerPresent: false,
    consentMechanismType: "none",
    cmpVendorName: null,
    cmpVendorConfidence: null,
    consentInteractionModel: "none",
    consentAcceptButtonCount: null,
    consentRejectButtonCount: null,
    consentPreferencesButtonCount: null,
    rejectAllPresent: false,
    acceptAllPresent: false,
    granularPreferencesPresent: false,
    preconsentTrackingDetected: true,
    cookiePolicyLinkedFromBanner: false,
    consentModeDetected: false,
    darkPatternAcceptEmphasis: false,
    darkPatternRejectHidden: false,
    darkPatternRejectButtonMissing: true,
    darkPatternAcceptButtonProminence: true,
    precheckedConsentBoxes: false,
    darkPatternForcedConsentWall: true,
    darkPatternAcceptOnlyBanner: true,
    darkPatternDismissWithoutReject: true,
    darkPatternCountdownTimerPresent: false,
    darkPatternFakeScarcityLanguage: false,
    consentSignatureHash: null,
    consentPersistenceMechanismDetected: null,
    consentBannerLayoutType: null,
    consentBannerPosition: null,
    defaultTrackingState: null,
    cookieCategoryCount: null,
    consentMaturityScore: null,
    trackerCountTotal: 0,
    analyticsTrackerCount: 0,
    advertisingTrackerCount: 0,
    socialTrackerCount: 0,
    sessionReplayTrackerCount: 0,
    tagManagerPresent: false,
    firstPartyAnalyticsOnly: false,
    adtechStackComplexityScore: 0,
    fingerprintingOrIdentityVendorDetected: false,
    trackerVendorSetHash: null,
    trackerCategorySetHash: null,
    trackerVendorConcentrationScore: null,
    trackerDiversityScore: null,
    thirdPartyScriptDomainCount: null,
    thirdPartyScriptRiskScore: null,
    thirdPartyDataFlowRiskScore: null,
    trackerRegulatoryRiskScore: null,
    trackerAdoptionChangeDetected: null,
    cookieCountTotal: 1,
    thirdPartyCookieCount: 0,
    firstPartyCookieSetBeforeConsent: null,
    thirdPartyCookieSetBeforeConsent: true,
    trackingBeforeConsentDetected: true,
    formCountTotal: 0,
    contactFormPresent: false,
    newsletterSignupPresent: false,
    accountSignupPresent: false,
    loginPagePresent: false,
    passwordResetPresent: false,
    checkoutOrPaymentFormPresent: false,
    fileUploadFieldPresent: false,
    emailInputPresent: false,
    phoneInputPresent: false,
    addressInputPresent: false,
    paymentCardInputPresent: false,
    dateOfBirthInputPresent: false,
    ageGatePresent: false,
    sensitiveDataFormHintsPresent: false,
    formCollectsBirthdate: false,
    parentalConsentReferencePresent: false,
    accessibilityContactMethodPresent: false,
    accessibilitySupportPathPresent: false,
    accessibilityWidgetPresent: false,
    vpatOrAccessibilityConformanceDocPresent: false,
    wcagErrorCountTotal: 0,
    wcagMissingAltCount: 0,
    wcagLandmarkIssueCount: 0,
    wcagFormLabelErrorCount: 0,
    wcagAriaErrorCount: 0,
    wcagLevelClaimed: null,
    wcagHeadingStructureErrorCount: 0,
    accessibilityClaimMismatchDetected: false,
    wcagLinkNameErrorCount: 0,
    accessibilityLitigationRiskScore: 0,
    adaDemandLetterProbability: 0,
    infrastructureChangeDetected: null,
    vulnerabilityDisclosurePagePresent: false,
    hstsEnabled: false,
    dmarcRecordPresent: false,
    securityHeaderPostureChanged: null,
    trustCenterPresent: false,
    responsibleDisclosurePresent: false,
    cspHeaderPresent: false,
    dkimRecordDetected: false,
    bugBountyProgramPresent: false,
    permissionsPolicyPresent: false,
    transparencyReportPresent: false,
    securityHeadersScore: 0,
    mixedContentDetected: false,
    aiAssistantWidgetDetected: false,
    aiHelpCenterAiReference: false,
    certscoreOverall: 78,
    privacyScore: 73,
    accessibilityScore: 100,
    consumerProtectionScore: 0,
    californiaExposureLikely: false,
    ecommerceSiteLikely: false,
    subprocessorListPresent: false,
    policyBehaviorConflictDetected: false,
    sessionReplayWithoutDisclosureDetected: false,
    userRightsFrictionScore: null,
    totalSignals: 6,
    ...overrides
  };
}

test("does not emit consent snapshot signals when no consent surface was observed", () => {
  const signals = projectSnapshotSignals(buildSnapshot(), []);
  const keys = signals.map((signal) => signal.key);

  assert.equal(keys.includes("privacy.preconsent_tracking_detected"), false);
  assert.equal(keys.includes("privacy.dark_pattern_reject_button_missing"), false);
  assert.equal(keys.includes("privacy.dark_pattern_accept_button_prominence"), false);
  assert.equal(keys.includes("privacy.dark_pattern_forced_consent_wall"), false);
  assert.equal(keys.includes("privacy.dark_pattern_accept_only_banner"), false);
  assert.equal(keys.includes("privacy.dark_pattern_dismiss_without_reject"), false);
});

test("emits consent snapshot signals when a consent surface was observed", () => {
  const signals = projectSnapshotSignals(
    buildSnapshot({
      cookieBannerPresent: true,
      consentMechanismType: "banner"
    }),
    []
  );
  const keys = signals.map((signal) => signal.key);

  assert.equal(keys.includes("privacy.preconsent_tracking_detected"), true);
  assert.equal(keys.includes("privacy.dark_pattern_accept_button_prominence"), true);
});
