// Generated by scripts/sync-gpc-observation-contract.ts; do not edit.
export const gpcActivityComparisonOpenApi = {
  "type": "object",
  "additionalProperties": false,
  "required": [
    "contractVersion",
    "scanId",
    "status",
    "scope",
    "durationMs",
    "sourceHashes",
    "activity",
    "scoreEffect",
    "causedByGpc"
  ],
  "properties": {
    "contractVersion": {
      "const": "certscore.gpc-activity-comparison.v1",
      "type": "string"
    },
    "scanId": {
      "type": "string",
      "minLength": 1,
      "maxLength": 200
    },
    "status": {
      "const": "measured",
      "type": "string"
    },
    "scope": {
      "const": "matched_post_commit_request_window",
      "type": "string"
    },
    "durationMs": {
      "anyOf": [
        {
          "const": 250,
          "type": "number"
        },
        {
          "const": 500,
          "type": "number"
        },
        {
          "const": 1000,
          "type": "number"
        }
      ]
    },
    "sourceHashes": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "baseline",
        "gpc"
      ],
      "properties": {
        "baseline": {
          "type": "string",
          "pattern": "^[a-f0-9]{64}$"
        },
        "gpc": {
          "type": "string",
          "pattern": "^[a-f0-9]{64}$"
        }
      }
    },
    "activity": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "advertisingMarketing",
        "analyticsReplay"
      ],
      "properties": {
        "advertisingMarketing": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "baselineRequests",
            "gpcRequests",
            "baselineServices",
            "gpcServices"
          ],
          "properties": {
            "baselineRequests": {
              "type": "integer",
              "minimum": 0,
              "maximum": 5000
            },
            "gpcRequests": {
              "type": "integer",
              "minimum": 0,
              "maximum": 5000
            },
            "baselineServices": {
              "type": "integer",
              "minimum": 0,
              "maximum": 5000
            },
            "gpcServices": {
              "type": "integer",
              "minimum": 0,
              "maximum": 5000
            }
          }
        },
        "analyticsReplay": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "baselineRequests",
            "gpcRequests",
            "baselineServices",
            "gpcServices"
          ],
          "properties": {
            "baselineRequests": {
              "type": "integer",
              "minimum": 0,
              "maximum": 5000
            },
            "gpcRequests": {
              "type": "integer",
              "minimum": 0,
              "maximum": 5000
            },
            "baselineServices": {
              "type": "integer",
              "minimum": 0,
              "maximum": 5000
            },
            "gpcServices": {
              "type": "integer",
              "minimum": 0,
              "maximum": 5000
            }
          }
        }
      }
    },
    "scoreEffect": {
      "const": "none",
      "type": "string"
    },
    "causedByGpc": {
      "const": "not_established",
      "type": "string"
    }
  }
} as const;
