// Generated by scripts/sync-gpc-observation-contract.ts; do not edit.
export const gpcBoundedObservationOpenApi = {
  "type": "object",
  "additionalProperties": false,
  "required": [
    "contractVersion",
    "scope",
    "status",
    "sourceSha256",
    "sessionSha256",
    "documentUrlSha256",
    "delivery",
    "semanticProbe",
    "registration",
    "acknowledgment",
    "requests",
    "limitationKeys",
    "scoreEffect",
    "legalInterpretation"
  ],
  "properties": {
    "contractVersion": {
      "const": "certscore.gpc-bounded-observation.v1",
      "type": "string"
    },
    "scope": {
      "const": "main_document_and_retained_http_requests",
      "type": "string"
    },
    "status": {
      "type": "string",
      "enum": [
        "complete",
        "limited",
        "unavailable"
      ]
    },
    "sourceSha256": {
      "anyOf": [
        {
          "type": "string",
          "pattern": "^[a-f0-9]{64}$"
        },
        {
          "type": "null"
        }
      ]
    },
    "sessionSha256": {
      "anyOf": [
        {
          "type": "string",
          "pattern": "^[a-f0-9]{64}$"
        },
        {
          "type": "null"
        }
      ]
    },
    "documentUrlSha256": {
      "anyOf": [
        {
          "type": "string",
          "pattern": "^[a-f0-9]{64}$"
        },
        {
          "type": "null"
        }
      ]
    },
    "delivery": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "httpHeaderRetained",
        "mainNavigatorReadbackRetained",
        "fullContextVerified"
      ],
      "properties": {
        "httpHeaderRetained": {
          "type": "boolean"
        },
        "mainNavigatorReadbackRetained": {
          "type": "boolean"
        },
        "fullContextVerified": {
          "type": "boolean"
        }
      }
    },
    "semanticProbe": {
      "type": "string",
      "enum": [
        "observed",
        "unsupported",
        "unavailable",
        "not_ready",
        "invalid",
        "incomplete"
      ]
    },
    "registration": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "basis",
        "sale",
        "sharing",
        "cmpGpcSignal",
        "causedByGpc"
      ],
      "properties": {
        "basis": {
          "const": "current_recorded_state",
          "type": "string"
        },
        "sale": {
          "type": "string",
          "enum": [
            "opted_out",
            "not_opted_out",
            "unknown"
          ]
        },
        "sharing": {
          "type": "string",
          "enum": [
            "opted_out",
            "not_opted_out",
            "unknown"
          ]
        },
        "cmpGpcSignal": {
          "type": "string",
          "enum": [
            "received",
            "not_received",
            "unknown"
          ]
        },
        "causedByGpc": {
          "const": "not_established",
          "type": "string"
        }
      }
    },
    "acknowledgment": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "observed",
        "captureComplete"
      ],
      "properties": {
        "observed": {
          "type": "boolean"
        },
        "captureComplete": {
          "type": "boolean"
        }
      }
    },
    "requests": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "count",
        "blockedBeforeTransmissionCount",
        "complete",
        "fromMs",
        "documentCommittedAtMs",
        "throughMs",
        "classifiedCount",
        "collectionCount",
        "evidenceIds",
        "samplesTruncated"
      ],
      "properties": {
        "count": {
          "type": "integer",
          "minimum": 0
        },
        "blockedBeforeTransmissionCount": {
          "type": "integer",
          "minimum": 0
        },
        "complete": {
          "type": "boolean"
        },
        "fromMs": {
          "anyOf": [
            {
              "type": "integer",
              "minimum": 0
            },
            {
              "type": "null"
            }
          ]
        },
        "documentCommittedAtMs": {
          "anyOf": [
            {
              "type": "integer",
              "minimum": 0
            },
            {
              "type": "null"
            }
          ]
        },
        "throughMs": {
          "anyOf": [
            {
              "type": "integer",
              "minimum": 0
            },
            {
              "type": "null"
            }
          ]
        },
        "classifiedCount": {
          "type": "integer",
          "minimum": 0
        },
        "collectionCount": {
          "type": "integer",
          "minimum": 0
        },
        "evidenceIds": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1,
            "maxLength": 160
          },
          "maxItems": 100
        },
        "samplesTruncated": {
          "type": "boolean"
        }
      }
    },
    "limitationKeys": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1,
        "maxLength": 160
      },
      "maxItems": 32
    },
    "scoreEffect": {
      "const": "none",
      "type": "string"
    },
    "legalInterpretation": {
      "const": "not_assessed",
      "type": "string"
    }
  }
} as const;
