// Generated by scripts/sync-gpc-observation-contract.ts; do not edit.
export const reportEvidencePageOpenApi = {
  "type": "object",
  "additionalProperties": false,
  "required": [
    "type",
    "version",
    "scanId",
    "snapshot",
    "reportUrl",
    "entries",
    "pagination",
    "coverage",
    "reconstruction"
  ],
  "properties": {
    "type": {
      "const": "certscore_report_evidence_page",
      "type": "string"
    },
    "version": {
      "const": 1,
      "type": "number"
    },
    "scanId": {
      "type": "string"
    },
    "snapshot": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "reportUrl": {
      "type": "string"
    },
    "workpaper": {
      "const": "tracking",
      "type": "string"
    },
    "section": {
      "type": "string",
      "enum": [
        "consent",
        "gpc",
        "policy",
        "tracking",
        "transport",
        "forms",
        "accessibility"
      ]
    },
    "selection": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "version",
        "fields",
        "notReturnedFields",
        "interpretation"
      ],
      "properties": {
        "version": {
          "const": "certscore.report-evidence-selection.v1",
          "type": "string"
        },
        "fields": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "maxItems": 30
        },
        "notReturnedFields": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "maxItems": 30
        },
        "interpretation": {
          "type": "string"
        }
      }
    },
    "download": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "url",
        "mediaType",
        "bytes",
        "authentication",
        "instructions"
      ],
      "properties": {
        "url": {
          "type": "string"
        },
        "csvUrl": {
          "type": "string"
        },
        "mediaType": {
          "const": "application/json",
          "type": "string"
        },
        "expiresAt": {
          "type": "string"
        },
        "bytes": {
          "type": "integer",
          "minimum": 0
        },
        "authentication": {
          "type": "string",
          "enum": [
            "same_access_rules_as_mcp",
            "short_lived_report_link",
            "public"
          ]
        },
        "instructions": {
          "type": "string"
        }
      }
    },
    "entries": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "path"
        ],
        "properties": {
          "path": {
            "type": "string"
          },
          "value": {},
          "stringPart": {
            "type": "integer",
            "minimum": 0
          },
          "stringParts": {
            "type": "integer",
            "minimum": 0
          }
        }
      }
    },
    "pagination": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "offset",
        "returned",
        "total",
        "complete",
        "nextCursor"
      ],
      "properties": {
        "offset": {
          "type": "integer",
          "minimum": 0
        },
        "returned": {
          "type": "integer",
          "minimum": 0
        },
        "total": {
          "type": "integer",
          "minimum": 0
        },
        "complete": {
          "type": "boolean"
        },
        "nextCursor": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        }
      }
    },
    "coverage": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "scope",
        "exportTruncated",
        "observationCompleteness",
        "exclusions"
      ],
      "properties": {
        "scope": {
          "const": "public_report_projection",
          "type": "string"
        },
        "exportTruncated": {
          "const": false,
          "type": "boolean"
        },
        "observationCompleteness": {
          "const": "see_report_coverage",
          "type": "string"
        },
        "exclusions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "reconstruction": {
      "type": "string"
    }
  }
} as const;
